name: Test Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '4.8.x'
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        
      - name: Restore NuGet packages
        run: nuget restore CSTestFramework.sln

      - name: Build solution
        run: msbuild CSTestFramework.sln /p:Configuration=Debug

      - name: Download Allure CommandLine
        run: |
          Invoke-WebRequest -Uri "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.zip" -OutFile "allure-commandline.zip"
          Expand-Archive -Path "allure-commandline.zip" -DestinationPath .
          Move-Item -Path "allure-2.24.1" -Destination "allure-commandline"

      - name: Download Allure History
        continue-on-error: true
        run: |
          mkdir allure-history
          Invoke-WebRequest -Uri "https://kryvokhatko.github.io/github.io/history/history.json" -OutFile "allure-history/history.json"
          Invoke-WebRequest -Uri "https://kryvokhatko.github.io/github.io/history/history-trend.json" -OutFile "allure-history/history-trend.json"
          Invoke-WebRequest -Uri "https://kryvokhatko.github.io/github.io/history/categories-trend.json" -OutFile "allure-history/categories-trend.json"
          Invoke-WebRequest -Uri "https://kryvokhatko.github.io/github.io/history/duration-trend.json" -OutFile "allure-history/duration-trend.json"
          Invoke-WebRequest -Uri "https://kryvokhatko.github.io/github.io/history/retry-trend.json" -OutFile "allure-history/retry-trend.json"

      - name: Run Tests
        shell: pwsh
        run: |
          $nunitPath = "packages\NUnit.ConsoleRunner.3.16.3\tools\nunit3-console.exe"
          $testDlls = Get-ChildItem -Recurse -Filter "*Tests.dll" -Path ".\**\bin\Debug" | Where-Object { $_.FullName -match 'bin\\Debug' }
          
          foreach ($dll in $testDlls) {
              Write-Host "Running tests in: $($dll.FullName)"
              & $nunitPath $dll.FullName `
                --framework="net-4.8" `
                --where="cat!=IgnoreOnCI" `
                --labels=Before `
                --trace=Debug `
                --result="TestResults.xml;format=nunit3" `
                --result="allure-results/allure-results.xml;format=nunit3"
          }

          # Convert NUnit results to TRX format using VSTest
          $trxPath = Join-Path $pwd "TestResults.trx"
          Write-Host "Generating TRX file at: $trxPath"
          vstest.console.exe @(Get-ChildItem -Recurse -Filter "*Tests.dll" -Path ".\**\bin\Debug" | Where-Object { $_.FullName -match 'bin\\Debug' }) /Logger:"trx;LogFileName=$trxPath"

          # Verify TRX file exists
          if (Test-Path $trxPath) {
              Write-Host "TRX file generated successfully at: $trxPath"
              Get-Content $trxPath | Select-Object -First 5
          } else {
              Write-Host "Warning: TRX file was not generated at: $trxPath"
          }

          Write-Host "Contents of allure-results directory:"
          Get-ChildItem "allure-results" -Recurse | ForEach-Object { Write-Host $_.FullName }

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ${{ github.workspace }}/TestResults.trx
          retention-days: 30

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
          retention-days: 30

      - name: Generate Allure Report
        if: always()
        run: |
          # Copy history if it exists
          if (Test-Path "allure-history") {
            Copy-Item -Path "allure-history/*" -Destination "allure-results" -Recurse -Force
          }
          
          # Generate report
          ./allure-commandline/bin/allure generate allure-results --clean -o allure-report
          
          # Copy report to GitHub Pages directory
          mkdir _site
          Copy-Item -Path "allure-report/*" -Destination "_site" -Recurse
          
          # Preserve history for next run
          mkdir -p _site/history
          Copy-Item -Path "allure-report/history/*" -Destination "_site/history" -Recurse -Force

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3

  deploy:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 